// ============================================================================
// soc.v — Complete RV32I System-on-Chip
// ============================================================================
//
// PURPOSE:
//   Top-level SoC integrating the RV32I processor core with:
//     - 80KB Block RAM (instruction + data memory)
//     - CLINT timer (machine-level interrupts)
//     - UART (TX + RX, memory-mapped)
//     - I2C master (SCCB mode)
//     - GPIO (bidirectional, configurable mode)
//     - Memory-mapped bus interconnect (Wishbone)
//
// MEMORY MAP:
//   0x0000_0000 – 0x0001_3FFF : Block RAM (80KB, device 0)
//   0x8000_0000 – 0x8000_004F : CLINT timer (device 1)
//   0x8000_0050 – 0x8000_009F : UART (device 2)
//   0x8000_00A0 – 0x8000_00EF : I2C  (device 3)
//   0x8000_00F0 – 0x8000_013F : GPIO (device 4)
//   0xC000_0000+              : DDR3 (device 5, optional)
//
// PARAMETERS:
//   CLK_FREQ_MHZ   : Clock frequency in MHz (for UART/I2C baud rate)
//   MEMORY_DEPTH   : Block RAM size in bytes (default 80KB = 81920)
//   BAUD_RATE      : UART baud rate (default 9600)
//   MEM_INIT_FILE  : Firmware HEX file path
//   GPIO_COUNT     : Number of GPIO pins (default 12)
//
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module soc #(
    parameter CLK_FREQ_MHZ    = 12,
    parameter PC_RESET        = 32'h00000000,
    parameter TRAP_ADDRESS    = 32'h00000000,
    parameter ZICSR_EXTENSION = 1,
    parameter MEMORY_DEPTH    = 81920,
    parameter GPIO_COUNT      = 12,
    parameter BAUD_RATE       = 9600,
    parameter MEM_INIT_FILE   = "memory.mem"
)(
    input  wire                    i_clk,      // System clock
    input  wire                    i_rst,      // Active-high reset

    // ── UART ──
    input  wire                    uart_rx,    // UART receive line
    output wire                    uart_tx,    // UART transmit line

    // ── I2C ──
    inout  wire                    i2c_sda,    // I2C data (bidirectional)
    inout  wire                    i2c_scl,    // I2C clock (bidirectional)

    // ── GPIO ──
    inout  wire [GPIO_COUNT-1:0]   gpio_pins   // General-purpose I/O
);

    // ════════════════════════════════════════════════
    //  CPU ↔ Memory Bus Wires
    // ════════════════════════════════════════════════

    // Instruction memory interface
    wire [31:0] inst;
    wire [31:0] iaddr;
    wire        stb_inst;
    wire        ack_inst;

    // Data memory interface (Wishbone)
    wire [31:0] wb_rdata;        // Read data from bus
    wire [31:0] wb_wdata;        // Write data from CPU
    wire [31:0] wb_addr;         // Address from CPU
    wire [3:0]  wb_sel;          // Byte strobes
    wire        wb_we;           // Write enable
    wire        wb_stb;          // Strobe (request)
    wire        wb_ack;          // Acknowledge
    wire        wb_cyc;          // Bus cycle
    wire        wb_stall;        // Stall

    // Interrupts
    wire        external_interrupt = 0;  // Not used (no external interrupt source)
    wire        timer_interrupt;
    wire        software_interrupt;

    // Per-device Wishbone bus signals (generated by bus interconnect)
    // Device 0: Block RAM
    wire        dev0_cyc, dev0_stb, dev0_we, dev0_ack, dev0_stall;
    wire [31:0] dev0_addr, dev0_wdata, dev0_rdata;
    wire [3:0]  dev0_sel;

    // Device 1: CLINT Timer
    wire        dev1_cyc, dev1_stb, dev1_we, dev1_ack, dev1_stall;
    wire [31:0] dev1_addr, dev1_wdata, dev1_rdata;
    wire [3:0]  dev1_sel;

    // Device 2: UART
    wire        dev2_cyc, dev2_stb, dev2_we, dev2_ack, dev2_stall;
    wire [31:0] dev2_addr, dev2_wdata, dev2_rdata;
    wire [3:0]  dev2_sel;

    // Device 3: I2C
    wire        dev3_cyc, dev3_stb, dev3_we, dev3_ack, dev3_stall;
    wire [31:0] dev3_addr, dev3_wdata, dev3_rdata;
    wire [3:0]  dev3_sel;

    // Device 4: GPIO
    wire        dev4_cyc, dev4_stb, dev4_we, dev4_ack, dev4_stall;
    wire [31:0] dev4_addr, dev4_wdata, dev4_rdata;
    wire [3:0]  dev4_sel;

    // Device 5: DDR3 (optional)
    wire        dev5_cyc, dev5_stb, dev5_we, dev5_ack, dev5_stall;
    wire [31:0] dev5_addr, dev5_wdata, dev5_rdata;
    wire [3:0]  dev5_sel;


    // ════════════════════════════════════════════════
    //  CPU Core
    // ════════════════════════════════════════════════
    core #(
        .PC_RESET        (PC_RESET),
        .TRAP_ADDRESS    (TRAP_ADDRESS),
        .ZICSR_EXTENSION (ZICSR_EXTENSION)
    ) u_core (
        .i_clk               (i_clk),
        .i_rst_n             (!i_rst),
        // Instruction memory
        .i_inst              (inst),
        .o_iaddr             (iaddr),
        .o_stb_inst          (stb_inst),
        .i_ack_inst          (ack_inst),
        // Data memory (Wishbone)
        .o_wb_cyc_data       (wb_cyc),
        .o_wb_stb_data       (wb_stb),
        .o_wb_we_data        (wb_we),
        .o_wb_addr_data      (wb_addr),
        .o_wb_data_data      (wb_wdata),
        .o_wb_sel_data       (wb_sel),
        .i_wb_ack_data       (wb_ack),
        .i_wb_stall_data     (wb_stall),
        .i_wb_data_data      (wb_rdata),
        // Interrupts
        .i_external_interrupt(external_interrupt),
        .i_software_interrupt(software_interrupt),
        .i_timer_interrupt   (timer_interrupt)
    );


    // ════════════════════════════════════════════════
    //  Bus Interconnect (Address Decoder)
    // ════════════════════════════════════════════════
    bus_interconnect u_bus (
        // CPU side
        .i_wb_cyc  (wb_cyc),   .i_wb_stb  (wb_stb),
        .i_wb_we   (wb_we),    .i_wb_addr (wb_addr),
        .i_wb_data (wb_wdata), .i_wb_sel  (wb_sel),
        .o_wb_ack  (wb_ack),   .o_wb_stall(wb_stall),
        .o_wb_data (wb_rdata),
        // Device 0 (RAM)
        .o_device0_wb_cyc(dev0_cyc), .o_device0_wb_stb(dev0_stb),
        .o_device0_wb_we(dev0_we),   .o_device0_wb_addr(dev0_addr),
        .o_device0_wb_data(dev0_wdata), .o_device0_wb_sel(dev0_sel),
        .i_device0_wb_ack(dev0_ack), .i_device0_wb_stall(dev0_stall),
        .i_device0_wb_data(dev0_rdata),
        // Device 1 (CLINT)
        .o_device1_wb_cyc(dev1_cyc), .o_device1_wb_stb(dev1_stb),
        .o_device1_wb_we(dev1_we),   .o_device1_wb_addr(dev1_addr),
        .o_device1_wb_data(dev1_wdata), .o_device1_wb_sel(dev1_sel),
        .i_device1_wb_ack(dev1_ack), .i_device1_wb_stall(dev1_stall),
        .i_device1_wb_data(dev1_rdata),
        // Device 2 (UART)
        .o_device2_wb_cyc(dev2_cyc), .o_device2_wb_stb(dev2_stb),
        .o_device2_wb_we(dev2_we),   .o_device2_wb_addr(dev2_addr),
        .o_device2_wb_data(dev2_wdata), .o_device2_wb_sel(dev2_sel),
        .i_device2_wb_ack(dev2_ack), .i_device2_wb_stall(dev2_stall),
        .i_device2_wb_data(dev2_rdata),
        // Device 3 (I2C)
        .o_device3_wb_cyc(dev3_cyc), .o_device3_wb_stb(dev3_stb),
        .o_device3_wb_we(dev3_we),   .o_device3_wb_addr(dev3_addr),
        .o_device3_wb_data(dev3_wdata), .o_device3_wb_sel(dev3_sel),
        .i_device3_wb_ack(dev3_ack), .i_device3_wb_stall(dev3_stall),
        .i_device3_wb_data(dev3_rdata),
        // Device 4 (GPIO)
        .o_device4_wb_cyc(dev4_cyc), .o_device4_wb_stb(dev4_stb),
        .o_device4_wb_we(dev4_we),   .o_device4_wb_addr(dev4_addr),
        .o_device4_wb_data(dev4_wdata), .o_device4_wb_sel(dev4_sel),
        .i_device4_wb_ack(dev4_ack), .i_device4_wb_stall(dev4_stall),
        .i_device4_wb_data(dev4_rdata),
        // Device 5 (DDR3)
        .o_device5_wb_cyc(dev5_cyc), .o_device5_wb_stb(dev5_stb),
        .o_device5_wb_we(dev5_we),   .o_device5_wb_addr(dev5_addr),
        .o_device5_wb_data(dev5_wdata), .o_device5_wb_sel(dev5_sel),
        .i_device5_wb_ack(dev5_ack), .i_device5_wb_stall(dev5_stall),
        .i_device5_wb_data(dev5_rdata)
    );


    // ════════════════════════════════════════════════
    //  Device 0: Block RAM (Instruction + Data)
    // ════════════════════════════════════════════════
    main_memory #(
        .MEMORY_DEPTH (MEMORY_DEPTH),
        .MEM_INIT_FILE(MEM_INIT_FILE)
    ) u_ram (
        .i_clk       (i_clk),
        .i_inst_addr (iaddr[$clog2(MEMORY_DEPTH)-1:0]),
        .o_inst_out  (inst),
        .i_stb_inst  (stb_inst),
        .o_ack_inst  (ack_inst),
        .i_wb_cyc    (dev0_cyc),
        .i_wb_stb    (dev0_stb),
        .i_wb_we     (dev0_we),
        .i_wb_addr   (dev0_addr[$clog2(MEMORY_DEPTH)-1:0]),
        .i_wb_data   (dev0_wdata),
        .i_wb_sel    (dev0_sel),
        .o_wb_ack    (dev0_ack),
        .o_wb_stall  (dev0_stall),
        .o_wb_data   (dev0_rdata)
    );


    // ════════════════════════════════════════════════
    //  Device 1: CLINT Timer
    // ════════════════════════════════════════════════
    clint #(
        .CLK_FREQ_MHZ          (CLK_FREQ_MHZ),
        .MTIME_BASE_ADDRESS    (32'h8000_0000),
        .MTIMECMP_BASE_ADDRESS (32'h8000_0008),
        .MSIP_BASE_ADDRESS     (32'h8000_0010)
    ) u_clint (
        .clk                 (i_clk),
        .rst_n               (!i_rst),
        .i_wb_cyc            (dev1_cyc),
        .i_wb_stb            (dev1_stb),
        .i_wb_we             (dev1_we),
        .i_wb_addr           (dev1_addr),
        .i_wb_data           (dev1_wdata),
        .i_wb_sel            (dev1_sel),
        .o_wb_ack            (dev1_ack),
        .o_wb_stall          (dev1_stall),
        .o_wb_data           (dev1_rdata),
        .o_timer_interrupt   (timer_interrupt),
        .o_software_interrupt(software_interrupt)
    );


    // ════════════════════════════════════════════════
    //  Device 2: UART (TX + RX)
    // ════════════════════════════════════════════════
    uart #(
        .CLOCK_FREQ       (CLK_FREQ_MHZ * 1_000_000),
        .BAUD_RATE        (BAUD_RATE),
        .UART_TX_DATA     (32'h8000_0050),
        .UART_TX_BUSY     (32'h8000_0054),
        .UART_RX_BUFFER_FULL(32'h8000_0058),
        .UART_RX_DATA     (32'h8000_005C),
        .DBIT             (8),
        .SBIT             (1)
    ) u_uart (
        .clk       (i_clk),
        .rst_n     (!i_rst),
        .i_wb_cyc  (dev2_cyc),
        .i_wb_stb  (dev2_stb),
        .i_wb_we   (dev2_we),
        .i_wb_addr (dev2_addr),
        .i_wb_data (dev2_wdata[7:0]),
        .i_wb_sel  (dev2_sel),
        .o_wb_ack  (dev2_ack),
        .o_wb_stall(dev2_stall),
        .o_wb_data (dev2_rdata[7:0]),
        .uart_rx   (uart_rx),
        .uart_tx   (uart_tx)
    );


    // ════════════════════════════════════════════════
    //  Device 3: I2C Master
    // ════════════════════════════════════════════════
    i2c #(
        .main_clock         (CLK_FREQ_MHZ * 1_000_000),
        .freq               (
            `ifdef ICARUS
                2_000_000
            `else
                100_000
            `endif
        ),
        .addr_bytes         (1),
        .I2C_START          (32'h8000_00A0),
        .I2C_WRITE          (32'h8000_00A4),
        .I2C_READ           (32'h8000_00A8),
        .I2C_BUSY           (32'h8000_00AC),
        .I2C_ACK            (32'h8000_00B0),
        .I2C_READ_DATA_READY(32'h8000_00B4),
        .I2C_STOP           (32'h8000_00B8)
    ) u_i2c (
        .clk       (i_clk),
        .rst_n     (!i_rst),
        .i_wb_cyc  (dev3_cyc),
        .i_wb_stb  (dev3_stb),
        .i_wb_we   (dev3_we),
        .i_wb_addr (dev3_addr),
        .i_wb_data (dev3_wdata[7:0]),
        .i_wb_sel  (dev3_sel),
        .o_wb_ack  (dev3_ack),
        .o_wb_stall(dev3_stall),
        .o_wb_data (dev3_rdata[7:0]),
        .scl       (i2c_scl),
        .sda       (i2c_sda)
    );


    // ════════════════════════════════════════════════
    //  Device 4: GPIO
    // ════════════════════════════════════════════════
    gpio #(
        .GPIO_MODE  (32'h8000_00F0),
        .GPIO_READ  (32'h8000_00F4),
        .GPIO_WRITE (32'h8000_00F8),
        .GPIO_COUNT (GPIO_COUNT)
    ) u_gpio (
        .clk       (i_clk),
        .rst_n     (!i_rst),
        .i_wb_cyc  (dev4_cyc),
        .i_wb_stb  (dev4_stb),
        .i_wb_we   (dev4_we),
        .i_wb_addr (dev4_addr),
        .i_wb_data (dev4_wdata[GPIO_COUNT-1:0]),
        .i_wb_sel  (dev4_sel),
        .o_wb_ack  (dev4_ack),
        .o_wb_stall(dev4_stall),
        .o_wb_data (dev4_rdata[GPIO_COUNT-1:0]),
        .gpio      (gpio_pins)
    );

endmodule


// ============================================================================
// bus_interconnect — Wishbone Address Decoder
// ============================================================================
// Routes CPU bus transactions to the correct peripheral based on address.
// Address bit [31] = 1 selects peripherals, = 0 selects RAM.
// Address bits [11:0] further select which peripheral.
// ============================================================================

module bus_interconnect (
    // ── CPU Side ──
    input  wire        i_wb_cyc,
    input  wire        i_wb_stb,
    input  wire        i_wb_we,
    input  wire [31:0] i_wb_addr,
    input  wire [31:0] i_wb_data,
    input  wire [3:0]  i_wb_sel,
    output reg         o_wb_ack,
    output reg         o_wb_stall,
    output reg  [31:0] o_wb_data,

    // ── Device 0: RAM ──
    output reg  o_device0_wb_cyc, o_device0_wb_stb, o_device0_wb_we,
    output reg  [31:0] o_device0_wb_addr, o_device0_wb_data,
    output reg  [3:0]  o_device0_wb_sel,
    input  wire i_device0_wb_ack, i_device0_wb_stall,
    input  wire [31:0] i_device0_wb_data,

    // ── Device 1: CLINT ──
    output reg  o_device1_wb_cyc, o_device1_wb_stb, o_device1_wb_we,
    output reg  [31:0] o_device1_wb_addr, o_device1_wb_data,
    output reg  [3:0]  o_device1_wb_sel,
    input  wire i_device1_wb_ack, i_device1_wb_stall,
    input  wire [31:0] i_device1_wb_data,

    // ── Device 2: UART ──
    output reg  o_device2_wb_cyc, o_device2_wb_stb, o_device2_wb_we,
    output reg  [31:0] o_device2_wb_addr, o_device2_wb_data,
    output reg  [3:0]  o_device2_wb_sel,
    input  wire i_device2_wb_ack, i_device2_wb_stall,
    input  wire [31:0] i_device2_wb_data,

    // ── Device 3: I2C ──
    output reg  o_device3_wb_cyc, o_device3_wb_stb, o_device3_wb_we,
    output reg  [31:0] o_device3_wb_addr, o_device3_wb_data,
    output reg  [3:0]  o_device3_wb_sel,
    input  wire i_device3_wb_ack, i_device3_wb_stall,
    input  wire [31:0] i_device3_wb_data,

    // ── Device 4: GPIO ──
    output reg  o_device4_wb_cyc, o_device4_wb_stb, o_device4_wb_we,
    output reg  [31:0] o_device4_wb_addr, o_device4_wb_data,
    output reg  [3:0]  o_device4_wb_sel,
    input  wire i_device4_wb_ack, i_device4_wb_stall,
    input  wire [31:0] i_device4_wb_data,

    // ── Device 5: DDR3 ──
    output reg  o_device5_wb_cyc, o_device5_wb_stb, o_device5_wb_we,
    output reg  [31:0] o_device5_wb_addr, o_device5_wb_data,
    output reg  [3:0]  o_device5_wb_sel,
    input  wire i_device5_wb_ack, i_device5_wb_stall,
    input  wire [31:0] i_device5_wb_data
);

    always @* begin
        // Default: all devices deselected
        o_wb_ack = 0;  o_wb_stall = 0;  o_wb_data = 0;

        {o_device0_wb_cyc, o_device0_wb_stb, o_device0_wb_we} = 0;
        o_device0_wb_addr = 0;  o_device0_wb_data = 0;  o_device0_wb_sel = 0;

        {o_device1_wb_cyc, o_device1_wb_stb, o_device1_wb_we} = 0;
        o_device1_wb_addr = 0;  o_device1_wb_data = 0;  o_device1_wb_sel = 0;

        {o_device2_wb_cyc, o_device2_wb_stb, o_device2_wb_we} = 0;
        o_device2_wb_addr = 0;  o_device2_wb_data = 0;  o_device2_wb_sel = 0;

        {o_device3_wb_cyc, o_device3_wb_stb, o_device3_wb_we} = 0;
        o_device3_wb_addr = 0;  o_device3_wb_data = 0;  o_device3_wb_sel = 0;

        {o_device4_wb_cyc, o_device4_wb_stb, o_device4_wb_we} = 0;
        o_device4_wb_addr = 0;  o_device4_wb_data = 0;  o_device4_wb_sel = 0;

        {o_device5_wb_cyc, o_device5_wb_stb, o_device5_wb_we} = 0;
        o_device5_wb_addr = 0;  o_device5_wb_data = 0;  o_device5_wb_sel = 0;

        if (i_wb_addr[31]) begin
            // ── Peripheral Space (address MSB = 1) ──
            if (i_wb_addr[11:0] < 12'h50) begin
                // Device 1: CLINT (0x8000_0000 – 0x8000_004F)
                o_device1_wb_cyc = i_wb_cyc;  o_device1_wb_stb = i_wb_stb;
                o_device1_wb_we = i_wb_we;    o_device1_wb_addr = i_wb_addr;
                o_device1_wb_data = i_wb_data; o_device1_wb_sel = i_wb_sel;
                o_wb_ack = i_device1_wb_ack;  o_wb_stall = i_device1_wb_stall;
                o_wb_data = i_device1_wb_data;
            end
            if (i_wb_addr[11:0] >= 12'h50 && i_wb_addr[11:0] < 12'hA0) begin
                // Device 2: UART (0x8000_0050 – 0x8000_009F)
                o_device2_wb_cyc = i_wb_cyc;  o_device2_wb_stb = i_wb_stb;
                o_device2_wb_we = i_wb_we;    o_device2_wb_addr = i_wb_addr;
                o_device2_wb_data = i_wb_data; o_device2_wb_sel = i_wb_sel;
                o_wb_ack = i_device2_wb_ack;  o_wb_stall = i_device2_wb_stall;
                o_wb_data = i_device2_wb_data;
            end
            if (i_wb_addr[11:0] >= 12'hA0 && i_wb_addr[11:0] < 12'hF0) begin
                // Device 3: I2C (0x8000_00A0 – 0x8000_00EF)
                o_device3_wb_cyc = i_wb_cyc;  o_device3_wb_stb = i_wb_stb;
                o_device3_wb_we = i_wb_we;    o_device3_wb_addr = i_wb_addr;
                o_device3_wb_data = i_wb_data; o_device3_wb_sel = i_wb_sel;
                o_wb_ack = i_device3_wb_ack;  o_wb_stall = i_device3_wb_stall;
                o_wb_data = i_device3_wb_data;
            end
            if (i_wb_addr[11:0] >= 12'hF0 && i_wb_addr[11:0] < 12'h140) begin
                // Device 4: GPIO (0x8000_00F0 – 0x8000_013F)
                o_device4_wb_cyc = i_wb_cyc;  o_device4_wb_stb = i_wb_stb;
                o_device4_wb_we = i_wb_we;    o_device4_wb_addr = i_wb_addr;
                o_device4_wb_data = i_wb_data; o_device4_wb_sel = i_wb_sel;
                o_wb_ack = i_device4_wb_ack;  o_wb_stall = i_device4_wb_stall;
                o_wb_data = i_device4_wb_data;
            end
            if (i_wb_addr[30]) begin
                // Device 5: DDR3 (0xC000_0000+)
                o_device5_wb_cyc = i_wb_cyc;  o_device5_wb_stb = i_wb_stb;
                o_device5_wb_we = i_wb_we;    o_device5_wb_addr = i_wb_addr;
                o_device5_wb_data = i_wb_data; o_device5_wb_sel = i_wb_sel;
                o_wb_ack = i_device5_wb_ack;  o_wb_stall = i_device5_wb_stall;
                o_wb_data = i_device5_wb_data;
            end
        end
        else begin
            // ── RAM Space (address MSB = 0) ──
            o_device0_wb_cyc = i_wb_cyc;  o_device0_wb_stb = i_wb_stb;
            o_device0_wb_we = i_wb_we;    o_device0_wb_addr = i_wb_addr;
            o_device0_wb_data = i_wb_data; o_device0_wb_sel = i_wb_sel;
            o_wb_ack = i_device0_wb_ack;  o_wb_stall = i_device0_wb_stall;
            o_wb_data = i_device0_wb_data;
        end
    end

endmodule


// ============================================================================
// main_memory — Combined Instruction + Data Block RAM
// ============================================================================
// Single-port BRAM with separate instruction read port.
// Firmware is loaded via $readmemh from MEM_INIT_FILE.
// ============================================================================

module main_memory #(
    parameter MEMORY_DEPTH  = 1024,
    parameter MEM_INIT_FILE = "memory.mem"
)(
    input  wire        i_clk,

    // ── Instruction Read Port ──
    input  wire [$clog2(MEMORY_DEPTH)-1:0] i_inst_addr,
    output reg  [31:0] o_inst_out,
    input  wire        i_stb_inst,
    output reg         o_ack_inst,

    // ── Data Read/Write Port (Wishbone) ──
    input  wire        i_wb_cyc,
    input  wire        i_wb_stb,
    input  wire        i_wb_we,
    input  wire [$clog2(MEMORY_DEPTH)-1:0] i_wb_addr,
    input  wire [31:0] i_wb_data,
    input  wire [3:0]  i_wb_sel,
    output reg         o_wb_ack,
    output wire        o_wb_stall,
    output reg  [31:0] o_wb_data
);

    reg [31:0] memory_regfile [MEMORY_DEPTH/4 - 1:0];

    assign o_wb_stall = 0;  // BRAM never stalls

    initial begin
        o_ack_inst <= 0;
        o_wb_ack   <= 0;
        o_inst_out <= 0;
        $readmemh(MEM_INIT_FILE, memory_regfile);
    end

    // Synchronous read (inferred as BRAM)
    always @(posedge i_clk) begin
        o_ack_inst <= i_stb_inst;
        o_wb_ack   <= i_wb_stb && i_wb_cyc;
        o_inst_out <= memory_regfile[i_inst_addr >> 2];
        o_wb_data  <= memory_regfile[i_wb_addr[$clog2(MEMORY_DEPTH)-1:2]];
    end

    // Byte-wise write
    always @(posedge i_clk) begin
        if (i_wb_we && i_wb_stb && i_wb_cyc) begin
            if (i_wb_sel[0]) memory_regfile[i_wb_addr[$clog2(MEMORY_DEPTH)-1:2]][7:0]   <= i_wb_data[7:0];
            if (i_wb_sel[1]) memory_regfile[i_wb_addr[$clog2(MEMORY_DEPTH)-1:2]][15:8]  <= i_wb_data[15:8];
            if (i_wb_sel[2]) memory_regfile[i_wb_addr[$clog2(MEMORY_DEPTH)-1:2]][23:16] <= i_wb_data[23:16];
            if (i_wb_sel[3]) memory_regfile[i_wb_addr[$clog2(MEMORY_DEPTH)-1:2]][31:24] <= i_wb_data[31:24];
        end
    end

endmodule


// ============================================================================
// uart — UART Transmitter + Receiver (8N1)
// ============================================================================
// Memory-mapped UART with TX and RX support.
// Uses 16x oversampling for reliable data recovery.
// ============================================================================

module uart #(
    parameter CLOCK_FREQ         = 12_000_000,
    parameter BAUD_RATE          = 9600,
    parameter UART_TX_DATA       = 8140,
    parameter UART_TX_BUSY       = 8144,
    parameter UART_RX_BUFFER_FULL = 8148,
    parameter UART_RX_DATA       = 8152,
    parameter DBIT               = 8,
    parameter SBIT               = 1
)(
    input  wire        clk,
    input  wire        rst_n,
    // Wishbone interface
    input  wire        i_wb_cyc,
    input  wire        i_wb_stb,
    input  wire        i_wb_we,
    input  wire [31:0] i_wb_addr,
    input  wire [DBIT-1:0] i_wb_data,
    input  wire [3:0]  i_wb_sel,
    output reg         o_wb_ack,
    output wire        o_wb_stall,
    output reg  [DBIT-1:0] o_wb_data,
    // UART lines
    input  wire        uart_rx,
    output wire        uart_tx
);

    localparam DVSR       = CLOCK_FREQ / (16 * BAUD_RATE);
    localparam DVSR_WIDTH = $clog2(DVSR);
    localparam SB_TICK    = 16 * SBIT;

    localparam [1:0] idle  = 2'd0,
                     start = 2'd1,
                     data  = 2'd2,
                     stop  = 2'd3;

    // TX registers
    reg [DBIT-1:0]       uart_busy;
    reg                  tx_done_tick;
    reg [1:0]            state_reg, state_nxt;
    reg [3:0]            s_reg, s_nxt;
    reg [2:0]            n_reg, n_nxt;
    reg [DBIT-1:0]       din_reg, din_nxt;
    reg                  tx_reg, tx_nxt;
    reg                  s_tick;
    reg                  wr_uart;

    // RX registers
    reg [1:0]            state_reg_rx, state_nxt_rx;
    reg [3:0]            s_reg_rx, s_nxt_rx;
    reg [2:0]            n_reg_rx, n_nxt_rx;
    reg [7:0]            b_reg, b_nxt;
    reg [7:0]            dout;
    reg                  rx_done_tick;
    reg                  rx_buffer_full;

    assign o_wb_stall = 0;

    // ── Baud Rate Generator (16x oversampling) ──
    reg [DVSR_WIDTH-1:0] counter = 0;
    always @(posedge clk, negedge rst_n) begin
        if (!rst_n) counter <= 0;
        else begin
            s_tick = 0;
            if (counter == DVSR - 1) begin
                s_tick  = 1;
                counter <= 0;
            end
            else counter <= counter + 1;
        end
    end

    // ── Memory-Mapped Register Read ──
    always @(posedge clk, negedge rst_n) begin
        if (!rst_n) begin
            o_wb_data <= 0;
            o_wb_ack  <= 0;
        end
        else begin
            if (i_wb_stb && i_wb_cyc && !i_wb_we && i_wb_addr == UART_TX_BUSY)
                o_wb_data <= uart_busy;
            else if (i_wb_stb && i_wb_cyc && !i_wb_we && i_wb_addr == UART_RX_BUFFER_FULL)
                o_wb_data <= rx_buffer_full;
            else if (i_wb_stb && i_wb_cyc && !i_wb_we && i_wb_addr == UART_RX_DATA)
                o_wb_data <= dout;
            o_wb_ack <= i_wb_stb && i_wb_cyc;
        end
    end

    // ── UART TX: FSM Registers ──
    always @(posedge clk, negedge rst_n) begin
        if (!rst_n) begin
            state_reg <= idle;  s_reg <= 0;  n_reg <= 0;
            din_reg   <= 0;    tx_reg <= 0;
        end
        else begin
            state_reg <= state_nxt;  s_reg <= s_nxt;  n_reg <= n_nxt;
            din_reg   <= din_nxt;    tx_reg <= tx_nxt;
        end
    end

    // ── UART TX: FSM Next-State Logic ──
    always @* begin
        state_nxt = state_reg;  s_nxt = s_reg;  n_nxt = n_reg;
        din_nxt = din_reg;  tx_nxt = tx_reg;
        tx_done_tick = 0;
        uart_busy = 1;
        case (state_reg)
            idle: begin
                tx_nxt = 1;
                uart_busy = 0;
                if (i_wb_we && i_wb_stb && i_wb_cyc && i_wb_addr == UART_TX_DATA && !uart_busy) begin
                    din_nxt   = i_wb_data;
                    s_nxt     = 0;
                    state_nxt = start;
                    uart_busy = 1;
                end
            end
            start: begin
                tx_nxt = 0;
                if (s_tick) begin
                    if (s_reg == 15) begin s_nxt = 0; n_nxt = 0; state_nxt = data; end
                    else s_nxt = s_reg + 1;
                end
            end
            data: begin
                tx_nxt = din_reg[0];
                if (s_tick) begin
                    if (s_reg == 15) begin
                        din_nxt = din_reg >> 1;  s_nxt = 0;
                        if (n_reg == DBIT - 1) state_nxt = stop;
                        else n_nxt = n_reg + 1;
                    end
                    else s_nxt = s_reg + 1;
                end
            end
            stop: begin
                tx_nxt = 1;
                if (s_tick) begin
                    if (s_reg == SB_TICK - 1) begin tx_done_tick = 1; state_nxt = idle; end
                    else s_nxt = s_reg + 1;
                end
            end
            default: state_nxt = idle;
        endcase
    end
    assign uart_tx = tx_reg;

    // ── UART RX: FSM Registers ──
    always @(posedge clk, negedge rst_n) begin
        if (!rst_n) begin
            state_reg_rx <= idle;  s_reg_rx <= 0;  n_reg_rx <= 0;
            b_reg <= 0;  dout <= 0;  rx_buffer_full <= 0;
        end
        else begin
            state_reg_rx <= state_nxt_rx;
            s_reg_rx     <= s_nxt_rx;
            n_reg_rx     <= n_nxt_rx;
            b_reg        <= b_nxt;
            if (rx_done_tick) begin
                dout           <= b_reg;
                rx_buffer_full <= 1'b1;
            end
            else if (i_wb_stb && i_wb_cyc && !i_wb_we && i_wb_addr == UART_RX_DATA)
                rx_buffer_full <= 1'b0;
        end
    end

    // ── UART RX: FSM Next-State Logic ──
    always @* begin
        state_nxt_rx = state_reg_rx;
        s_nxt_rx = s_reg_rx;  n_nxt_rx = n_reg_rx;  b_nxt = b_reg;
        rx_done_tick = 0;
        case (state_reg_rx)
            idle:  if (uart_rx == 0) begin s_nxt_rx = 0; state_nxt_rx = start; end
            start: if (s_tick) begin
                if (s_reg_rx == 7) begin s_nxt_rx = 0; n_nxt_rx = 0; state_nxt_rx = data; end
                else s_nxt_rx = s_reg_rx + 1;
            end
            data: if (s_tick) begin
                if (s_reg_rx == 15) begin
                    b_nxt = {uart_rx, b_reg[7:1]};  s_nxt_rx = 0;
                    if (n_reg_rx == DBIT - 1) state_nxt_rx = stop;
                    else n_nxt_rx = n_reg_rx + 1;
                end
                else s_nxt_rx = s_reg_rx + 1;
            end
            stop: if (s_tick) begin
                if (s_reg_rx == SB_TICK - 1) begin rx_done_tick = 1; state_nxt_rx = idle; end
                else s_nxt_rx = s_reg_rx + 1;
            end
            default: state_nxt_rx = idle;
        endcase
    end

endmodule


// ============================================================================
// i2c — I2C Master Controller (SCCB Mode)
// ============================================================================
// Supports write and read transactions via memory-mapped registers.
// Uses IOBUF for bidirectional SDA line on FPGA.
// ============================================================================

module i2c #(
    parameter main_clock = 12_000_000,
    parameter freq       = 100_000,
    parameter addr_bytes = 2,
    parameter I2C_START           = 8100,
    parameter I2C_WRITE           = 8104,
    parameter I2C_READ            = 8108,
    parameter I2C_BUSY            = 8112,
    parameter I2C_ACK             = 8116,
    parameter I2C_READ_DATA_READY = 8120,
    parameter I2C_STOP            = 8124
)(
    input  wire        clk,
    input  wire        rst_n,
    input  wire        i_wb_cyc,
    input  wire        i_wb_stb,
    input  wire        i_wb_we,
    input  wire [31:0] i_wb_addr,
    input  wire [7:0]  i_wb_data,
    input  wire [3:0]  i_wb_sel,
    output reg         o_wb_ack,
    output wire        o_wb_stall,
    output reg  [7:0]  o_wb_data,
    inout  wire        scl, sda
);

    wire [7:0] i2c_busy = {7'b0, !((state_q == idle) || (state_q == stop_or_write) || (state_q == stop_or_read))};
    wire [7:0] i2c_read_data_ready = {7'b0, (state_q == stop_or_read)};
    reg  [7:0] i2c_ack;
    reg  [7:0] i2c_stop;

    wire       start = i_wb_stb && i_wb_cyc;
    wire [7:0] wr_data = i_wb_data;
    reg        ack;
    reg        rd_tick;

    localparam full          = (main_clock) / (2 * freq),
               half          = full / 2,
               counter_width = $clog2(full);

    localparam [3:0] idle          = 0,
                     starting      = 1,
                     packet        = 2,
                     ack_servant   = 3,
                     read          = 4,
                     ack_master    = 5,
                     stop_1        = 6,
                     stop_2        = 7,
                     stop_or_read  = 8,
                     stop_or_write = 9;

    reg [3:0]  state_q = idle, state_d;
    reg        op_q = 0, op_d;
    reg [3:0]  idx_q = 0, idx_d;
    reg [8:0]  wr_data_q = 0, wr_data_d;
    reg [7:0]  rd_data_q, rd_data_d;
    reg        scl_q = 0, scl_d;
    reg        sda_q = 0, sda_d;
    reg [counter_width-1:0] counter_q = 0, counter_d;
    reg [1:0]  addr_bytes_q = 0, addr_bytes_d;
    wire       scl_lo, scl_hi;
    wire       sda_in, sda_out;

    assign o_wb_stall = 0;

    // Memory-mapped register access
    always @(posedge clk, negedge rst_n) begin
        if (!rst_n) begin
            i2c_stop <= 0;  o_wb_ack <= 0;
        end
        else begin
            if (i_wb_stb && i_wb_cyc && i_wb_we  && i_wb_addr == I2C_STOP)            i2c_stop  <= i_wb_data;
            if (i_wb_stb && i_wb_cyc && !i_wb_we && i_wb_addr == I2C_ACK)             o_wb_data <= i2c_ack;
            if (i_wb_stb && i_wb_cyc && !i_wb_we && i_wb_addr == I2C_READ_DATA_READY) o_wb_data <= i2c_read_data_ready;
            if (i_wb_stb && i_wb_cyc && !i_wb_we && i_wb_addr == I2C_BUSY)            o_wb_data <= i2c_busy;
            if (i_wb_stb && i_wb_cyc && !i_wb_we && i_wb_addr == I2C_READ)            o_wb_data <= rd_data_q;
            o_wb_ack <= i_wb_stb && i_wb_cyc;
        end
    end

    // Register operations
    always @(posedge clk, negedge rst_n) begin
        if (!rst_n) begin
            state_q <= idle;  idx_q <= 0;  wr_data_q <= 0;
            scl_q <= 0;  sda_q <= 0;  counter_q <= 0;
            rd_data_q <= 0;  addr_bytes_q <= 0;  i2c_ack <= 0;
        end
        else begin
            state_q <= state_d;  op_q <= op_d;  idx_q <= idx_d;
            wr_data_q <= wr_data_d;  scl_q <= scl_d;  sda_q <= sda_d;
            if (i2c_busy[0]) counter_q <= counter_d;
            rd_data_q <= rd_data_d;  addr_bytes_q <= addr_bytes_d;
            i2c_ack <= {7'd0, ack};
        end
    end

    // Free-running SCL clock
    always @* begin
        counter_d = counter_q + 1;
        scl_d = scl_q;
        if (state_q == idle || state_q == starting) scl_d = 1'b1;
        else if (counter_q == full[counter_width-1:0]) begin
            counter_d = 0;
            scl_d = (scl_q == 0) ? 1'b1 : 1'b0;
        end
    end

    // I2C FSM next-state logic
    always @* begin
        state_d = state_q;  op_d = op_q;  idx_d = idx_q;
        wr_data_d = wr_data_q;  rd_data_d = rd_data_q;
        addr_bytes_d = addr_bytes_q;  sda_d = sda_q;
        rd_tick = 0;  ack = i2c_ack[0];

        case (state_q)
            idle: begin
                sda_d = 1'b1;  addr_bytes_d = addr_bytes;
                if (start && i_wb_we && i_wb_addr == I2C_START) begin
                    wr_data_d = {wr_data, 1'b1};
                    op_d = (wr_data[0]) ? 1 : 0;
                    idx_d = 8;  state_d = starting;
                end
            end
            starting: if (scl_hi) begin sda_d = 0; state_d = packet; end
            packet: if (scl_lo) begin
                sda_d = (wr_data_q[idx_q] == 0) ? 0 : 1'b1;
                idx_d = idx_q - 1;
                if (idx_q == 0) begin state_d = ack_servant; idx_d = 0; end
            end
            ack_servant: if (scl_hi) begin
                ack = !sda_in;
                if (i2c_stop[0]) state_d = stop_1;
                else if (op_q) begin idx_d = 7; state_d = read; end
                else begin state_d = stop_or_write; idx_d = 8; end
            end
            stop_or_write: begin
                if (i2c_stop[0]) state_d = stop_1;
                else if (start && i_wb_we && i_wb_addr == I2C_WRITE) begin
                    state_d = packet;  wr_data_d = {wr_data, 1'b1};
                    addr_bytes_d = addr_bytes_q - 1;
                end
            end
            read: if (scl_hi) begin
                rd_data_d[idx_q[2:0]] = sda_in;
                idx_d = idx_q - 1;
                if (idx_q == 0) state_d = ack_master;
            end
            ack_master: if (scl_lo) begin
                sda_d = 1'b0;
                if (sda_q == 0) begin
                    rd_tick = 1;  idx_d = 7;
                    if (i2c_stop[0]) state_d = stop_1;
                    else state_d = stop_or_read;
                end
            end
            stop_or_read: begin
                if (i2c_stop[0]) state_d = stop_1;
                else if (start && !i_wb_we && i_wb_addr == I2C_READ)
                    state_d = read;
            end
            stop_1: if (scl_lo) begin sda_d = 1'b0; state_d = stop_2; end
            stop_2: if (scl_hi) begin sda_d = 1'b1; state_d = idle; end
            default: state_d = idle;
        endcase
    end

    // I2C I/O (SCCB mode — no pull-ups needed)
    wire is_reading = (state_q == read || state_q == ack_servant);
    assign sda_out = sda_q;

    `ifndef ICARUS
        IOBUF sda_iobuf (
            .IO(sda), .I(sda_out), .T(is_reading), .O(sda_in)
        );
    `endif
    `ifdef ICARUS
        assign sda = sda_q;
    `endif

    assign scl    = scl_q;
    assign scl_hi = scl_q == 1'b1 && counter_q == half[counter_width-1:0];
    assign scl_lo = scl_q == 1'b0 && counter_q == half[counter_width-1:0];

endmodule


// ============================================================================
// clint — Core Local Interruptor (Machine-Level Timer)
// ============================================================================
// Provides mtime, mtimecmp (timer interrupt), and msip (software interrupt).
// Timer interrupt fires when mtime >= mtimecmp.
// ============================================================================

module clint #(
    parameter CLK_FREQ_MHZ          = 12,
    parameter MTIME_BASE_ADDRESS    = 8008,
    parameter MTIMECMP_BASE_ADDRESS = 8016,
    parameter MSIP_BASE_ADDRESS     = 8024
)(
    input  wire        clk,
    input  wire        rst_n,
    input  wire        i_wb_cyc,
    input  wire        i_wb_stb,
    input  wire        i_wb_we,
    input  wire [31:0] i_wb_addr,
    input  wire [31:0] i_wb_data,
    input  wire [3:0]  i_wb_sel,
    output reg         o_wb_ack,
    output wire        o_wb_stall,
    output reg  [31:0] o_wb_data,
    output wire        o_timer_interrupt,
    output wire        o_software_interrupt
);

    reg [63:0] mtime    = 0;
    reg [63:0] mtimecmp = {64{1'b1}};
    reg        msip     = 0;

    assign o_wb_stall          = 0;
    assign o_timer_interrupt   = (mtime >= mtimecmp);
    assign o_software_interrupt = msip;

    // Read
    always @(posedge clk, negedge rst_n) begin
        if (!rst_n) begin o_wb_ack <= 0; o_wb_data <= 0; end
        else begin
            if (i_wb_stb && i_wb_cyc && !i_wb_we) begin
                if      (i_wb_addr == MTIME_BASE_ADDRESS)       o_wb_data <= mtime[31:0];
                else if (i_wb_addr == MTIME_BASE_ADDRESS + 4)   o_wb_data <= mtime[63:32];
                if      (i_wb_addr == MTIMECMP_BASE_ADDRESS)    o_wb_data <= mtimecmp[31:0];
                else if (i_wb_addr == MTIMECMP_BASE_ADDRESS + 4) o_wb_data <= mtimecmp[63:32];
                if      (i_wb_addr == MSIP_BASE_ADDRESS)        o_wb_data <= {31'b0, msip};
            end
            o_wb_ack <= i_wb_stb && i_wb_cyc;
        end
    end

    // Write + timer increment
    always @(posedge clk, negedge rst_n) begin
        if (!rst_n) begin
            mtime    <= 0;
            mtimecmp <= {64{1'b1}};
            msip     <= 0;
        end
        else begin
            if (i_wb_stb && i_wb_cyc && i_wb_we) begin
                if      (i_wb_addr == MTIME_BASE_ADDRESS)        mtime[31:0]    <= i_wb_data;
                else if (i_wb_addr == MTIME_BASE_ADDRESS + 4)    mtime[63:32]   <= i_wb_data;
                if      (i_wb_addr == MTIMECMP_BASE_ADDRESS)     mtimecmp[31:0] <= i_wb_data;
                else if (i_wb_addr == MTIMECMP_BASE_ADDRESS + 4) mtimecmp[63:32] <= i_wb_data;
                if      (i_wb_addr == MSIP_BASE_ADDRESS)         msip <= i_wb_data[0];
            end
            mtime <= mtime + 1;
        end
    end

endmodule


// ============================================================================
// gpio — General-Purpose Input/Output Controller
// ============================================================================
// Memory-mapped GPIO with configurable direction (read/write per pin).
// Uses IOBUF primitives on FPGA for bidirectional pins.
// ============================================================================

module gpio #(
    parameter GPIO_MODE  = 32'hF0,
    parameter GPIO_READ  = 32'hF4,
    parameter GPIO_WRITE = 32'hF8,
    parameter GPIO_COUNT = 12
)(
    input  wire        clk,
    input  wire        rst_n,
    input  wire        i_wb_cyc,
    input  wire        i_wb_stb,
    input  wire        i_wb_we,
    input  wire [31:0] i_wb_addr,
    input  wire [GPIO_COUNT-1:0] i_wb_data,
    input  wire [3:0]  i_wb_sel,
    output reg         o_wb_ack,
    output wire        o_wb_stall,
    output reg  [GPIO_COUNT-1:0] o_wb_data,
    inout  wire [11:0] gpio
);

    reg [GPIO_COUNT-1:0] gpio_reg;
    reg [GPIO_COUNT-1:0] gpio_write;
    wire [GPIO_COUNT-1:0] gpio_read;
    reg [GPIO_COUNT-1:0] gpio_mode;

    assign o_wb_stall = 0;

    always @(posedge clk, negedge rst_n) begin
        if (!rst_n) begin
            gpio_write <= 0;  gpio_mode <= 0;  gpio_reg <= 0;
        end
        else begin
            if (i_wb_stb && i_wb_we  && i_wb_addr == GPIO_MODE)  gpio_mode  <= i_wb_data;
            if (i_wb_stb && !i_wb_we && i_wb_addr == GPIO_MODE)  o_wb_data  <= gpio_mode;
            if (i_wb_stb && i_wb_we  && i_wb_addr == GPIO_WRITE) gpio_write <= i_wb_data;
            if (i_wb_stb && !i_wb_we && i_wb_addr == GPIO_WRITE) o_wb_data  <= gpio_write;
            if (i_wb_stb && !i_wb_we && i_wb_addr == GPIO_READ)  o_wb_data  <= gpio_read;
            o_wb_ack <= i_wb_stb;
        end
    end

    `ifndef ICARUS
        genvar i;
        generate
            for (i = 0; i < GPIO_COUNT; i = i + 1) begin
                IOBUF gpio_iobuf (
                    .IO(gpio[i]),
                    .I(gpio_write[i]),
                    .T(!gpio_mode[i]),
                    .O(gpio_read[i])
                );
            end
        endgenerate
    `else
        genvar i;
        for (i = 0; i < GPIO_COUNT; i = i + 1) begin
            assign gpio[i] = gpio_mode[i] ? gpio_write[i] : 1'bz;
        end
    `endif

endmodule
